name: digital14_flutter_task
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_spinkit: ^5.1.0
  # https://pub.dev/packages/get_it
  # License: MIT
  get_it: ^7.2.0
  # https://pub.dev/packages/get
  # License: MIT
  get: ^4.6.5
  # https://pub.dev/packages/flutter_overlay_loader
  # License: Apache 2.0
  flutter_overlay_loader: ^2.0.0
  # https://pub.dev/packages/flutter_bloc
  # License: MIT
  flutter_bloc: ^8.0.1
  # https://pub.dev/packages/retrofit
  # License: MIT
  retrofit: ^3.0.1+1
  # https://pub.dev/packages/shared_preferences
  # License: BSD
  shared_preferences: ^2.0.15
  # https://pub.dev/packages/json_annotation
  # BSD-3
  json_annotation: ^4.5.0
  # https://pub.dev/packages/dio
  # MIT
  dio: ^4.0.6
  # https://pub:dev/packages/cupertino_icons:
  # MIT
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  # License: BSD
  flutter_lints: ^1.0.4
  # https://pub.dev/packages/json_serializaFble
  # License: BSD
  json_serializable: ^6.0.1
  # https://pub.dev/packages/retrofit_generator
  # License: MIT
  retrofit_generator:
  # https://pub.dev/packages/build_runner
  # License: BSD
  build_runner: ^2.1.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: pt